ALTER TABLE apikeys
ADD COLUMN IF NOT EXISTS hamwiz_api VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;

CREATE TABLE IF NOT EXISTS bard_wa_chatbot (
   id INT AUTO_INCREMENT PRIMARY KEY,
   uid VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   title VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   client_id VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   train_data LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   send_in_group INT(1) DEFAULT NULL,
   active INT(1) DEFAULT 1,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS custom_reply_flow (
   id INT AUTO_INCREMENT PRIMARY KEY,
   uid VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   group_id VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   incoming_message LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   outgoing_message LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   exact INT(1) DEFAULT NULL,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS custom_reply_flow_group (
   id INT AUTO_INCREMENT PRIMARY KEY,
   uid VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   group_id VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   title VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hamWiz_avatar (
   id INT AUTO_INCREMENT PRIMARY KEY,
   uid VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   job_id VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   image VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   status VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hamWiz_img (
   id INT AUTO_INCREMENT PRIMARY KEY,
   uid VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   job_id VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   prompt LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   negative_prompt LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   image VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   bgRem VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   status VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hamWiz_upscale (
   id INT AUTO_INCREMENT PRIMARY KEY,
   uid VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   job_id VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   old_image VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   upscaled_image VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   status VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO payment_gateways (active, code, payment_id, payment_keys, name)
VALUES (0, 'stripe', 'xxxx', 'xxxx', 'Stripe');

ALTER TABLE plan
ADD COLUMN IF NOT EXISTS allow_own_openai INT(1) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS upload_media (
   id INT AUTO_INCREMENT PRIMARY KEY,
   uid VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   file VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user
ADD COLUMN IF NOT EXISTS use_my_openai INT(1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS my_openai_api VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bard_one VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bard_two VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bard_three VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;

CREATE TABLE IF NOT EXISTS wa_ai_bot (
    id INT AUTO_INCREMENT PRIMARY KEY,
    active INT(1) DEFAULT 1,
    uid VARCHAR(999) DEFAULT NULL,
    bot_title VARCHAR(999) DEFAULT NULL,
    client_id VARCHAR(999) DEFAULT NULL,
    text_train_data LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    doc_text_train LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    train_type VARCHAR(999) DEFAULT NULL,
    group_id VARCHAR(999) DEFAULT NULL,
    reaction VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    enable_typing INT(1) DEFAULT 1,
    openai_model VARCHAR(999) DEFAULT NULL,
    sql_connection LONGTEXT DEFAULT NULL,
    train_data_instruction LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    reply_in_groups INT(1) DEFAULT 1,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE user
ADD COLUMN IF NOT EXISTS gemini_keys VARCHAR(999) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS gemini_chatbot (
   id INT AUTO_INCREMENT PRIMARY KEY,
   active INT(1) DEFAULT 1,
   uid VARCHAR(999) DEFAULT NULL,
   bot_title VARCHAR(999) DEFAULT NULL,
   client_id VARCHAR(999) DEFAULT NULL,
   text_train_data LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
   reaction VARCHAR(999) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
   enable_typing INT(1) DEFAULT 1,
   reply_in_groups INT(1) DEFAULT 1,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE plan
ADD COLUMN IF NOT EXISTS gemini_chatbot INT(1) DEFAULT 1